In [103]:
import numpy as np
from sklearn.datasets import load_boston
from sklearn import metrics
from sklearn import preprocessing

In [131]:
X,y = load_boston(return_X_y=True)
X_train_temp1 = X[0:400,:]
dummy = np.ones((X_train_temp1.shape[0],1)) 
X_train = np.c_[dummy,X_train_temp1]
y_train = y[0:400]

X_test_temp1 = X[400:,:]
dummy1 = np.ones((X_test_temp1.shape[0],1)) 
X_test = np.c_[dummy1,X_test_temp1]
y_test = y[400:]

X_train = preprocessing.normalize(X_train)
X_test = preprocessing.normalize(X_test)
y_train = y_train/y_train.max()
y_test = y_test/y_test.max()

In [132]:
X_train.min()

0.0

In [133]:
u = y_train.reshape(400,1)
y_train = preprocessing.normalize(u)

In [134]:
y = y_train/y_train.max()

In [135]:
X_train.shape

(400, 14)

In [144]:

n = X_train.shape[1] #no_of_feature 
theta = np.random.random_sample((n, 1))
num_epochs = 20
learning_rate = 0.001
for i in range(num_epochs):
    np.random.shuffle(y_train)
    np.random.shuffle(X_train)
    for j in range(len(y_train)):
        y_act = y_train[j].reshape(1,1) 
        array = X_train[j].reshape(14,1)
        y_pred = np.dot(theta.T,array)
        theta = theta - (learning_rate *(y_pred - y_act)*array)
        print((y_pred - y_act))
       # print(theta)

[[-0.47404648]]
[[-0.47892465]]
[[-0.48106903]]
[[-0.47471459]]
[[-0.49086255]]
[[-0.50967883]]
[[-0.47268309]]
[[-0.46785594]]
[[-0.49206208]]
[[-0.45234609]]
[[-0.46446933]]
[[-0.48417633]]
[[-0.46981881]]
[[-0.44004472]]
[[-0.47726285]]
[[-0.47702309]]
[[-0.46190022]]
[[-0.48677777]]
[[-0.48218159]]
[[-0.49355887]]
[[-0.46805321]]
[[-0.4859311]]
[[-0.47381094]]
[[-0.46765793]]
[[-0.47083704]]
[[-0.47997167]]
[[-0.47023369]]
[[-0.49429641]]
[[-0.44361254]]
[[-0.46238896]]
[[-0.50221438]]
[[-0.47315233]]
[[-0.45500452]]
[[-0.47012642]]
[[-0.46508262]]
[[-0.47793384]]
[[-0.47437543]]
[[-0.44164723]]
[[-0.46677368]]
[[-0.45133175]]
[[-0.47913083]]
[[-0.45425066]]
[[-0.47713852]]
[[-0.44318897]]
[[-0.46194547]]
[[-0.4475864]]
[[-0.4494287]]
[[-0.47104172]]
[[-0.44810416]]
[[-0.44979943]]
[[-0.45445443]]
[[-0.43715278]]
[[-0.45638959]]
[[-0.48421029]]
[[-0.44245982]]
[[-0.49672414]]
[[-0.46357315]]
[[-0.45874757]]
[[-0.44413697]]
[[-0.43903824]]
[[-0.42967691]]
[[-0.36908969]]
[[-0.456429

[[-0.29279663]]
[[-0.25433474]]
[[-0.30120731]]
[[-0.26647667]]
[[-0.26422904]]
[[-0.26314621]]
[[-0.30486575]]
[[-0.34112821]]
[[-0.28316914]]
[[-0.27432979]]
[[-0.25484109]]
[[-0.29931686]]
[[-0.25167294]]
[[-0.29306533]]
[[-0.2589201]]
[[-0.28756604]]
[[-0.27366337]]
[[-0.28379464]]
[[-0.27960393]]
[[-0.29070613]]
[[-0.27275937]]
[[-0.26470331]]
[[-0.28965781]]
[[-0.29792241]]
[[-0.28402313]]
[[-0.30245336]]
[[-0.28092112]]
[[-0.29418394]]
[[-0.29316002]]
[[-0.27754315]]
[[-0.27431677]]
[[-0.26244298]]
[[-0.29059922]]
[[-0.27472709]]
[[-0.27903877]]
[[-0.2681885]]
[[-0.28426526]]
[[-0.29297707]]
[[-0.2645825]]
[[-0.28868432]]
[[-0.25608194]]
[[-0.27858803]]
[[-0.28155124]]
[[-0.267137]]
[[-0.2915028]]
[[-0.26607906]]
[[-0.28964812]]
[[-0.28709708]]
[[-0.25432989]]
[[-0.28265021]]
[[-0.25377131]]
[[-0.24927855]]
[[-0.28215489]]
[[-0.2515311]]
[[-0.27740461]]
[[-0.25470962]]
[[-0.27606722]]
[[-0.24914195]]
[[-0.28476489]]
[[-0.26213604]]
[[-0.28700332]]
[[-0.28173943]]
[[-0.28267656]]

[[-0.16995922]]
[[-0.14234851]]
[[-0.15240465]]
[[-0.141644]]
[[-0.14831221]]
[[-0.16020097]]
[[-0.13588495]]
[[-0.17327953]]
[[-0.16647669]]
[[-0.16756964]]
[[-0.135953]]
[[-0.16010941]]
[[-0.17399426]]
[[-0.14524372]]
[[-0.18575134]]
[[-0.15039534]]
[[-0.15751339]]
[[-0.1606023]]
[[-0.14835567]]
[[-0.17359664]]
[[-0.18820764]]
[[-0.15321614]]
[[-0.17814308]]
[[-0.1472477]]
[[-0.17316858]]
[[-0.20393955]]
[[-0.13487801]]
[[-0.16443392]]
[[-0.13610135]]
[[-0.18251637]]
[[-0.17913176]]
[[-0.14118661]]
[[-0.17810928]]
[[-0.15316213]]
[[-0.19477443]]
[[-0.15713467]]
[[-0.13625709]]
[[-0.14743815]]
[[-0.13674021]]
[[-0.15916484]]
[[-0.16048541]]
[[-0.14265714]]
[[-0.13626414]]
[[-0.12277666]]
[[-0.14522937]]
[[-0.18372007]]
[[-0.116595]]
[[-0.16539215]]
[[-0.12666009]]
[[-0.19535821]]
[[-0.17458594]]
[[-0.13414602]]
[[-0.15048288]]
[[-0.15813429]]
[[-0.17028309]]
[[-0.11602887]]
[[-0.1483392]]
[[-0.1744939]]
[[-0.14068169]]
[[-0.25472124]]
[[-0.13104181]]
[[-0.14761581]]
[[-0.17225264]]
[[

[[-0.08835871]]
[[-0.09745066]]
[[-0.0734241]]
[[-0.03332648]]
[[-0.05084284]]
[[-0.03253003]]
[[-0.05228349]]
[[-0.06025937]]
[[-0.08747226]]
[[-0.07683698]]
[[-0.07033465]]
[[-0.02221638]]
[[-0.04781474]]
[[-0.03074234]]
[[-0.04556496]]
[[-0.10075143]]
[[-0.05797459]]
[[-0.06666691]]
[[-0.04384738]]
[[-0.0273379]]
[[-0.06617604]]
[[-0.05908722]]
[[-0.0532774]]
[[-0.05608716]]
[[-0.01810032]]
[[-0.03604071]]
[[-0.04977226]]
[[-0.04582258]]
[[-0.07760738]]
[[-0.08604791]]
[[-0.07570455]]
[[-0.02292886]]
[[-0.04219647]]
[[-0.05398182]]
[[-0.0343186]]
[[-0.03509249]]
[[-0.06061578]]
[[-0.07096918]]
[[-0.05071116]]
[[-0.05270722]]
[[-0.05217913]]
[[-0.07228479]]
[[-0.05119595]]
[[-0.04737876]]
[[-0.04489734]]
[[-0.04625468]]
[[-0.05521123]]
[[-0.05482734]]
[[-0.04519981]]
[[-0.04506016]]
[[-0.17853362]]
[[-0.05226602]]
[[-0.03551342]]
[[-0.03189427]]
[[-0.05524037]]
[[-0.04146082]]
[[-0.01401279]]
[[-0.06678235]]
[[-0.08139325]]
[[-0.06350543]]
[[-0.03227471]]
[[-0.03820491]]
[[-0.0729862

[[-0.0484289]]
[[-0.01718778]]
[[-0.06133161]]
[[-0.02121633]]
[[-0.01774143]]
[[-0.05237759]]
[[-0.03083608]]
[[-0.00645195]]
[[-0.04910685]]
[[-0.00660921]]
[[-0.0107353]]
[[-0.0351627]]
[[-0.03941515]]
[[-0.05685587]]
[[-0.0404789]]
[[-0.01841887]]
[[-0.00911631]]
[[-0.06202329]]
[[-0.01360717]]
[[-0.00813988]]
[[-0.02003413]]
[[-0.04000318]]
[[-0.03903363]]
[[-0.00186974]]
[[-0.03535369]]
[[-0.03104525]]
[[-0.01038807]]
[[-0.05882793]]
[[-0.01341255]]
[[-0.01687684]]
[[-0.02108097]]
[[-0.04674378]]
[[-0.03522433]]
[[0.00046029]]
[[-0.03305612]]
[[-0.03150228]]
[[-0.04575586]]
[[-0.04460993]]
[[-0.02012955]]
[[-0.03002558]]
[[-0.02152854]]
[[-0.05380083]]
[[-0.03456332]]
[[-0.04031225]]
[[-0.00975375]]
[[-0.05685556]]
[[-0.02304436]]
[[-0.03238591]]
[[0.03504807]]
[[-0.05186522]]
[[-0.03250955]]
[[-0.01742329]]
[[-0.04228466]]
[[-0.07457312]]
[[-0.03275503]]
[[-0.02443956]]
[[-0.02467673]]
[[-0.04582096]]
[[-0.02235161]]
[[-0.02030005]]
[[-0.01604187]]
[[-0.02899726]]
[[-0.01882649]

[[0.00462312]]
[[-0.00358634]]
[[-0.04542528]]
[[0.00188522]]
[[-0.02086829]]
[[-0.04503236]]
[[-0.02178679]]
[[-0.01462961]]
[[-0.02304413]]
[[-0.01054599]]
[[-0.11947691]]
[[-0.02013811]]
[[-0.02585216]]
[[7.30573416e-05]]
[[-0.01673444]]
[[-0.02057524]]
[[-0.04109705]]
[[-0.01865045]]
[[-0.04941744]]
[[0.00032209]]
[[-0.03533672]]
[[-0.03753789]]
[[-0.00631693]]
[[-0.0437431]]
[[0.00874249]]
[[-0.02060686]]
[[-0.02476023]]
[[-0.02902664]]
[[-0.02602763]]
[[-0.01755418]]
[[0.03020278]]
[[-0.02979144]]
[[-0.01242159]]
[[-0.02335358]]
[[-0.01140098]]
[[0.01173012]]
[[-0.01494901]]
[[-0.02415794]]
[[-0.03512937]]
[[-0.02480361]]
[[-0.04415886]]
[[-0.00883356]]
[[-0.03381371]]
[[-0.01019533]]
[[-0.03940778]]
[[-0.0174519]]
[[0.02343154]]
[[-0.03263053]]
[[0.00918981]]
[[-0.00457604]]
[[-0.05419438]]
[[-0.04503854]]
[[-0.03156294]]
[[-0.02457939]]
[[-0.02731141]]
[[-0.0352345]]
[[-0.01803723]]
[[-0.00259799]]
[[-0.01042006]]
[[-0.00315594]]
[[0.00227332]]
[[-0.03553774]]
[[-0.01805143]]
[

[[-0.00656087]]
[[-0.02089804]]
[[-0.02600314]]
[[-0.01397458]]
[[-0.03373718]]
[[-0.0116958]]
[[-0.00694449]]
[[-0.00927022]]
[[-0.01684624]]
[[-0.01131786]]
[[-0.0122702]]
[[-0.01009428]]
[[-0.0008357]]
[[-0.02422861]]
[[-0.02780221]]
[[-0.00064612]]
[[0.00079068]]
[[-0.0016073]]
[[-0.01092801]]
[[0.00524175]]
[[-0.05473925]]
[[0.0104482]]
[[0.0063855]]
[[-0.01877998]]
[[-0.00633046]]
[[0.03798769]]
[[-0.01844475]]
[[-0.03715989]]
[[-0.01820754]]
[[-0.0237375]]
[[-0.01811357]]
[[-0.01789154]]
[[0.01664663]]
[[-0.02601477]]
[[-0.03645235]]
[[0.02310322]]
[[-0.02878322]]
[[-0.01091714]]
[[-0.02194455]]
[[-0.01708593]]
[[0.00444351]]
[[-0.11243684]]
[[-0.01077002]]
[[-0.0302969]]
[[-0.0410017]]
[[-0.03607209]]
[[-0.03361421]]
[[-0.00169632]]
[[-0.00507059]]
[[-0.01309029]]
[[0.02096254]]
[[-0.13801432]]
[[0.00194367]]
[[0.01060833]]
[[0.00018396]]
[[-0.01644426]]
[[0.00702704]]
[[-0.00391537]]
[[0.00710112]]
[[-0.02016762]]
[[0.0094762]]
[[-0.03656602]]
[[0.0316838]]
[[-0.01918917]]
[[0

[[-0.02618639]]
[[-0.01937583]]
[[-0.00108597]]
[[-0.02588076]]
[[-0.02712991]]
[[0.00010873]]
[[0.00394509]]
[[0.01978576]]
[[-0.0404405]]
[[-0.00950789]]
[[-0.02528978]]
[[0.02951448]]
[[-0.00783065]]
[[-0.03512923]]
[[-0.04193863]]
[[0.01950668]]
[[-0.03236923]]
[[0.00406642]]
[[-0.00237042]]
[[-0.0120521]]
[[0.02330662]]
[[-0.11231154]]
[[0.00912107]]
[[-0.01796609]]
[[0.02740241]]
[[-0.001592]]
[[-0.01499926]]
[[0.00597696]]
[[-0.00259254]]
[[-0.00080093]]
[[-0.0097283]]
[[0.01320214]]
[[0.01791514]]
[[-0.03320519]]
[[-0.00200752]]
[[-0.00463085]]
[[0.0291645]]
[[-0.042814]]
[[0.04268538]]
[[-0.02200213]]
[[-0.05091357]]
[[-0.03536459]]
[[-0.03441004]]
[[-0.00604946]]
[[-0.02188137]]
[[0.00903716]]
[[-0.05434417]]
[[-0.00622976]]
[[0.02309657]]
[[-0.02593883]]
[[0.00216216]]
[[-0.01243266]]
[[0.00552802]]
[[-0.00991739]]
[[-0.00501908]]
[[-0.0274968]]
[[-0.01923353]]
[[-0.0125884]]
[[-0.13419479]]
[[-0.0274198]]
[[-0.00857881]]
[[-0.00902745]]
[[0.01136719]]
[[-0.03156689]]
[[-0.0

[[0.00396636]]
[[0.0211581]]
[[0.00173198]]
[[-0.00583981]]
[[-0.00098089]]
[[-0.00689006]]
[[-0.00106776]]
[[0.01267907]]
[[-0.00120814]]
[[0.00742296]]
[[0.01314167]]
[[-0.01863913]]
[[-0.00455452]]
[[0.02040518]]
[[-0.01768482]]
[[0.03289534]]
[[-0.01693773]]
[[-0.01302816]]
[[-0.01961949]]
[[0.0193494]]
[[-0.0031248]]
[[-0.03000189]]
[[0.00629546]]
[[0.02908714]]
[[-0.02216784]]
[[-0.03325422]]
[[-0.13554948]]
[[-0.00239409]]
[[-0.02203258]]
[[-0.02247053]]
[[0.06237003]]
[[-0.00447242]]
[[-0.02786184]]
[[-0.01399773]]
[[0.02500219]]
[[-0.02451866]]
[[-0.02031037]]
[[0.01667122]]
[[-0.00501491]]
[[-0.01336065]]
[[0.0335174]]
[[0.01952529]]
[[-0.02889418]]
[[0.00092528]]
[[0.01129856]]
[[0.00373252]]
[[0.0057556]]
[[0.0317787]]
[[-0.00357925]]
[[0.01863155]]
[[-0.04768952]]
[[-0.01563771]]
[[0.00518951]]
[[0.01531244]]
[[-0.01367175]]
[[0.02612907]]
[[0.00651926]]
[[0.0142839]]
[[-0.01151412]]
[[-0.0097807]]
[[0.011852]]
[[0.01326655]]
[[0.0111255]]
[[0.0233689]]
[[0.0092699]]
[[0.0

[[-0.02284214]]
[[0.00946802]]
[[-0.02983306]]
[[0.00162703]]
[[0.01303524]]
[[-0.01148566]]
[[-0.01168934]]
[[-0.0316556]]
[[0.00329371]]
[[-0.00806936]]
[[-0.02862392]]
[[-0.01505]]
[[-0.01560645]]
[[0.01617112]]
[[-0.01276636]]
[[-0.01274512]]
[[-0.02944042]]
[[0.01244704]]
[[0.00750586]]
[[-0.00723607]]
[[0.01947026]]
[[-0.02264591]]
[[-0.04744116]]
[[-0.01020694]]
[[-0.02461221]]
[[-0.01733639]]
[[-0.04171001]]
[[-0.02821943]]
[[-0.00245407]]
[[0.01048824]]
[[-0.00153898]]
[[-0.02469696]]
[[-0.00532321]]
[[0.01855191]]
[[-0.00074511]]
[[-0.00865881]]
[[0.01577268]]
[[-0.00069041]]
[[-0.13029376]]
[[-0.02748919]]
[[0.01818654]]
[[0.01939901]]
[[-0.13412759]]
[[0.00032667]]
[[0.01109697]]
[[0.00239594]]
[[-0.01598261]]
[[-0.00826019]]
[[-0.02681978]]
[[0.00169282]]
[[0.03470579]]
[[-0.01924653]]
[[0.03535088]]
[[0.00111936]]
[[-0.02472803]]
[[0.00078118]]
[[-0.01652407]]
[[-0.00409614]]
[[0.00360582]]
[[-0.01255867]]
[[0.00973482]]
[[0.00507924]]
[[0.01516973]]
[[-0.01231706]]
[[0.0

[[0.01622271]]
[[-0.00358375]]
[[0.00478145]]
[[0.00771753]]
[[-0.00359098]]
[[0.02690425]]
[[-0.02529834]]
[[0.00488543]]
[[-0.0103729]]
[[-0.0036158]]
[[-0.1073]]
[[-0.00533822]]
[[-0.01104157]]
[[-0.0105916]]
[[0.00127188]]
[[0.02349263]]
[[-0.01704824]]
[[0.0086699]]
[[0.02288395]]
[[0.01364869]]
[[-0.02299322]]
[[0.01676155]]
[[0.02247889]]
[[-0.01283898]]
[[0.01712365]]
[[0.01673799]]
[[-0.02868592]]
[[-0.02632258]]
[[0.02050583]]
[[-0.02248405]]
[[0.00224751]]
[[-0.02842037]]
[[-0.02640885]]
[[0.0081087]]
[[0.03019808]]
[[-0.0139801]]
[[0.00590633]]
[[-0.00629013]]
[[0.01549474]]
[[-0.01406721]]
[[-0.02973303]]
[[0.0142111]]
[[-0.03122678]]
[[-0.00253264]]
[[0.06471708]]
[[0.01155816]]
[[-0.0173027]]
[[-0.02391841]]
[[0.00988599]]
[[-0.01945258]]
[[-0.02061559]]
[[0.00023474]]
[[0.01660686]]
[[0.00474276]]
[[-0.01726736]]
[[-0.00041721]]
[[-0.01296682]]
[[0.0154345]]
[[-0.02610854]]
[[-0.00129523]]
[[0.00976818]]
[[0.00015541]]
[[-0.0065166]]
[[0.03604196]]
[[-0.02276618]]
[[0.0

[[-0.02358868]]
[[0.04005007]]
[[-0.00905714]]
[[-0.00593306]]
[[-0.13292956]]
[[0.02285601]]
[[0.00607084]]
[[0.04880952]]
[[-0.01161492]]
[[-0.0245924]]
[[0.0060232]]
[[-0.04508572]]
[[0.02270178]]
[[-6.20144647e-05]]
[[-0.00450962]]
[[-0.01547727]]
[[-0.01410253]]
[[-0.0420234]]
[[0.01496223]]
[[-0.00139773]]
[[-0.01589116]]
[[0.01555024]]
[[-0.00290141]]
[[-0.02211062]]
[[0.00098101]]
[[-0.00675033]]
[[0.00366559]]
[[-0.03387479]]
[[0.01619748]]
[[0.02479383]]
[[-0.00324102]]
[[0.02773368]]
[[-0.01900505]]
[[0.01189099]]
[[0.00200701]]
[[-0.01685226]]
[[-0.01936384]]
[[0.0089158]]
[[0.00417894]]
[[0.0182116]]
[[0.01234254]]
[[-0.0252275]]
[[0.00700844]]
[[0.00049391]]
[[0.01942954]]
[[0.03537859]]
[[-0.01507538]]
[[0.01025587]]
[[-0.00631975]]
[[0.01840842]]
[[0.00922217]]
[[0.02361709]]
[[0.009207]]
[[-0.00612327]]
[[-0.02276831]]
[[-0.01014057]]
[[0.02098179]]
[[-0.00601308]]
[[-0.01204632]]
[[-0.00261885]]
[[-0.02850957]]
[[-0.00191164]]
[[0.02316988]]
[[0.00847331]]
[[-0.003650

In [146]:
theta

array([[0.10911454],
       [0.81600371],
       [0.18461169],
       [0.48100184],
       [0.34447764],
       [0.84441797],
       [0.10553905],
       [0.36707452],
       [0.64812474],
       [0.60928167],
       [0.63310737],
       [0.49584016],
       [0.67327788],
       [0.44035084]])

In [87]:
y_act = y_train[4].reshape(1,1) 
array = X_train[4].reshape(14,1)
y_pred = np.dot(theta.T,array)
theta = theta - (learning_rate *(y_pred - y_act)*array)
print(y_act)
print(array)
print(y_pred)

[[36.2]]
[[1.0000e+00]
 [6.9050e-02]
 [0.0000e+00]
 [2.1800e+00]
 [0.0000e+00]
 [4.5800e-01]
 [7.1470e+00]
 [5.4200e+01]
 [6.0622e+00]
 [3.0000e+00]
 [2.2200e+02]
 [1.8700e+01]
 [3.9690e+02]
 [5.3300e+00]]
[[-5.47179786e+14]]


In [79]:
array = array.reshape(14,)
theta = theta.reshape(14,)
np.dot(theta.T,array)

array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan, nan,
       nan])

In [31]:
a = y_train[0].reshape(1,1)

In [32]:
a

array([[24.]])